# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('stock_shorter_name', models.CharField(max_length=20)),
                ('announcement_date', models.DateTimeField()),
                ('announcement_type', models.CharField(max_length=10)),
                ('announcement_content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('RMB_ordinary_stock', models.IntegerField()),
                ('domestically_listed_foreign_capital_shares', models.IntegerField()),
                ('foreign_capital_shares_listed_overseas', models.IntegerField()),
                ('state_owned_shares', models.IntegerField()),
                ('total_shared', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('stock_shorter_name', models.CharField(max_length=20)),
                ('company_full_name', models.CharField(max_length=30)),
                ('company_english_name', models.CharField(max_length=30)),
                ('registered_address', models.CharField(max_length=40)),
                ('legal_representative', models.CharField(max_length=20)),
                ('industry_type', models.CharField(max_length=10)),
                ('listed_time', models.DateTimeField()),
                ('IPO_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Excutive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(max_length=6)),
                ('highest_qualification', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IpoIinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('IPO_time', models.DateTimeField()),
                ('issued_sum', models.IntegerField()),
                ('issued_price', models.FloatField()),
                ('financing_amount', models.FloatField()),
                ('issued_earning_rate', models.FloatField()),
                ('issued_method', models.CharField(max_length=10)),
                ('main_underwriter', models.CharField(max_length=20)),
                ('success_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorFinancialIndicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('stock_shorter_name', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('reporting_period', models.CharField(max_length=10)),
                ('basic_earning_per_share', models.FloatField()),
                ('net_asset_per_share', models.FloatField()),
                ('flow_rate', models.FloatField()),
                ('asset_liability_ratio', models.FloatField()),
                ('net_profit_margins', models.FloatField()),
                ('total_assets_ratio', models.FloatField()),
                ('near_assets_ratio', models.FloatField()),
                ('fixed_assets_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorShareholdersIncreaseOrDecrease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('stock_shorter_name', models.CharField(max_length=20)),
                ('shareholder_name', models.CharField(max_length=10)),
                ('announcement_date', models.DateTimeField()),
                ('new_price', models.FloatField()),
                ('rise_or_fall_ratio', models.IntegerField()),
                ('rise_or_fall', models.CharField(max_length=5)),
                ('change_amount', models.IntegerField()),
                ('proportion_of_tradable_share', models.FloatField()),
                ('total_number_shares_held', models.IntegerField()),
                ('proportion_of_total_share', models.FloatField()),
                ('proportion_of_tradable_shares', models.FloatField()),
                ('change_start_date', models.DateTimeField()),
                ('change_end_date', models.DateTimeField()),
            ],
        ),
    ]
