# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_title',
            field=models.CharField(default='\u516c\u544a', max_length=30),
        ),
    ]
