# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_announcement_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_title',
            field=models.CharField(default='announcement_title', max_length=30),
        ),
    ]
