# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20160818_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalstructure',
            name='announcement_date',
            field=models.DateField(default=datetime.date(2016, 8, 19)),
        ),
        migrations.AddField(
            model_name='capitalstructure',
            name='change_date',
            field=models.DateField(default=datetime.date(2016, 8, 19)),
        ),
        migrations.AddField(
            model_name='capitalstructure',
            name='change_reason',
            field=models.CharField(default='reason', max_length=100),
        ),
    ]
