# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20160819_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorshareholdersincreaseordecrease',
            name='proportion_of_total_share',
        ),
        migrations.RemoveField(
            model_name='majorshareholdersincreaseordecrease',
            name='proportion_of_tradable_share',
        ),
        migrations.RemoveField(
            model_name='majorshareholdersincreaseordecrease',
            name='proportion_of_tradable_shares',
        ),
        migrations.RemoveField(
            model_name='majorshareholdersincreaseordecrease',
            name='total_number_shares_held',
        ),
        migrations.AddField(
            model_name='majorshareholdersincreaseordecrease',
            name='new_proportion_of_total_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='majorshareholdersincreaseordecrease',
            name='new_proportion_of_tradable_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='majorshareholdersincreaseordecrease',
            name='new_total_number_shares_held',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='majorshareholdersincreaseordecrease',
            name='old_proportion_of_total_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='majorshareholdersincreaseordecrease',
            name='old_proportion_of_tradable_shares',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateTimeField(default=datetime.date(2016, 8, 19)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateTimeField(default=datetime.date(2016, 8, 19)),
        ),
    ]
