# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20160819_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateField(default=datetime.date(2016, 8, 19)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateField(default=datetime.date(2016, 8, 19)),
        ),
    ]
