# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20160819_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalstructure',
            name='announcement_date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='change_date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
        migrations.AlterField(
            model_name='ipoiinfo',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo'),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateField(default=datetime.date(2016, 8, 22)),
        ),
    ]
