# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20160822_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorfinancialindicy',
            old_name='year',
            new_name='announce_year',
        ),
    ]
