# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20160822_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEN', models.CharField(max_length=20)),
                ('nameCN', models.CharField(max_length=20)),
                ('continent', models.CharField(choices=[('AS', 'Asia'), ('EU', 'Europe'), ('AF', 'Africa'), ('SA', 'South America'), ('NS', 'Nouth America'), ('OA', 'Oceania')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEN', models.CharField(max_length=20)),
                ('shortnameEN', models.CharField(max_length=10)),
                ('nameCN', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.FloatField()),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CountriesData')),
                ('index_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Index')),
            ],
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='registered_capital',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='announcement_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 2, 59, 3, 690000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 2, 59, 3, 690000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo'),
        ),
        migrations.AlterField(
            model_name='majorfinancialindicy',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo'),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 2, 59, 3, 706000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 2, 59, 3, 706000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo'),
        ),
    ]
