# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20161011_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='frequency',
            field=models.CharField(choices=[('Y', 'Year'), ('Q', 'Quarter'), ('M', 'Month')], default='Year', max_length=20),
        ),
        migrations.AddField(
            model_name='indexdata',
            name='data_months',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexdata',
            name='data_years',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='announcement_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 5, 59, 11, 991000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 5, 59, 11, 991000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 5, 59, 11, 994000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 5, 59, 11, 994000, tzinfo=utc)),
        ),
    ]
