# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20161011_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriesdata',
            name='indexs',
            field=models.ManyToManyField(through='company.IndexData', to='company.Index'),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='announcement_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 1, 12, 43, 416000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 1, 12, 43, 416000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 1, 12, 43, 419000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 1, 12, 43, 419000, tzinfo=utc)),
        ),
    ]
