# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20161012_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalstructure',
            name='announcement_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 8, 8, 29, 323000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 8, 8, 29, 323000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='stock_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='countriesdata',
            name='nameEN',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='index',
            name='nameEN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ipoiinfo',
            name='stock_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='majorfinancialindicy',
            name='stock_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_end_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 8, 8, 29, 326000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='change_start_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 8, 8, 29, 326000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='majorshareholdersincreaseordecrease',
            name='stock_id',
            field=models.CharField(max_length=10),
        ),
    ]
